__version__ = "0.0.7"
# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_testcell.ipynb.

# %% auto 0
__all__ = ['global_skip', 'global_use_banner', 'params', 'skip_message_box', 'testcell_message_box', 'noglobals_message_box',
           'MessageBox', 'testcell', 'testcelln']

# %% ../nbs/02_testcell.ipynb 4
import ast
from IPython.core.magic import register_cell_magic, needs_local_scope
from IPython import get_ipython # needed for quarto
from IPython.display import Code

# %% ../nbs/02_testcell.ipynb 5
from .core import auto_return

# %% ../nbs/02_testcell.ipynb 6
global_skip = False # If true all %%testcell cells will be skipped
global_use_banner = False # if true it shows a banner on the cell's output

# Expose colors array to enable customization
params = {
    'testcell_background':'yellow', 'testcell_text':'black', 'testcell_emoji':'🟡',
    'noglobals_background':'green', 'noglobals_text':'white', 'noglobals_emoji':'🟢',
    'skip_background':'#808080', 'skip_text':'white', 'skip_emoji':'ℹ️',   
}

# %% ../nbs/02_testcell.ipynb 8
# Temporary class to deal with different display options (jupyter or console)
class MessageBox:
    def __init__(self,data,*,background_color,text_color,emoji=None):
        self.data = data
        self.background_color = background_color
        self.text_color = text_color
        self.emoji = emoji

    def _repr_html_(self):
        return f"""
        <div style="background-color: {self.background_color}; padding: 3px; text-align: center; font-size: 12px; color: {self.text_color};">
            {self.data}
        </div>
        """

    def __repr__(self): 
        text = self.data
        if self.emoji is not None: text = self.emoji + " " + text
        return text

# %% ../nbs/02_testcell.ipynb 9
skip_message_box= MessageBox('This cell has been skipped',background_color=params['skip_background'],text_color=params['skip_text'],emoji=params['skip_emoji'])
testcell_message_box = MessageBox("testcell",background_color=params['testcell_background'],text_color=params['testcell_text'],emoji=params['testcell_emoji'])
noglobals_message_box = MessageBox("testcell noglobals",background_color=params['noglobals_background'],text_color=params['noglobals_text'],emoji=params['noglobals_emoji'])

# %% ../nbs/02_testcell.ipynb 13
@register_cell_magic
@needs_local_scope
def testcell(line, cell, local_ns):
    # Parse arguments
    verbose = 'verbose' in line # enable verbose 
    dryrun = 'dryrun' in line # this will avoid running the code and just print out the code like verbose
    noglobals = 'noglobals' in line # no access to global variables, this enables 'noreturn' too 
    noreturn = 'noreturn' in line # display but does not return anything, so no memory "footprint" after execution
    skip = ('skip' in line) or global_skip # skip cell execution
    use_banner = ('banner' in line) or global_use_banner # shows a contextual banner at top of the cell
    
    # arguments rules
    if noglobals or dryrun: noreturn=True
    if dryrun: verbose=True

    # skip
    if skip: 
        display(skip_message_box)
        return None # exits

    
    # Do the job
    cell = auto_return(cell)
    lines = cell.splitlines()

    # Wrap inside a function and execute it
    arr = ['def _test_cell_():']
    arr += ['\t'+x for x in lines]
    arr += ['try:\n\t_ = _test_cell_()'] # execute it and assign result to '_'
    arr += ['finally:\n\tdel _test_cell_'] # delete it
    if noreturn:
        arr += ['if _ is not None: display(_)'] # having this as last line makes the same behavior as normal cell        
    else:
        arr += ['_ # This will be added to global scope'] # having this as last line makes the same behavior as normal cell
    wrapped_cell = '\n'.join(arr)

    if verbose: display(Code('\n### BEGIN\n'+wrapped_cell+'\n### END',language='python'))

    _globals = {} if noglobals else local_ns
    _locals = {'_':None} if noreturn else None # we mask '_' with a local variable to prevent it affecting global scope
    if not 'dryrun' in line: 
        if use_banner: display(noglobals_message_box if noglobals else testcell_message_box)
        exec(wrapped_cell,_globals,_locals)
    
    return None if noreturn else _globals.get('_',None) # this closes the loop of integration

# %% ../nbs/02_testcell.ipynb 17
@register_cell_magic
@needs_local_scope
def testcelln(line, cell, local_ns):
    return testcell(line=line+ ' noglobals', cell=cell, local_ns=local_ns)
