# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testcell',
                'doc_host': 'https://artste.github.io',
                'git_url': 'https://github.com/artste/testcell',
                'lib_path': 'testcell'},
  'syms': { 'testcell.core': { 'testcell.core.auto_display': ('ast.html#auto_display', 'testcell/core.py'),
                               'testcell.core.code_till_node': ('ast.html#code_till_node', 'testcell/core.py'),
                               'testcell.core.is_assignment': ('ast.html#is_assignment', 'testcell/core.py'),
                               'testcell.core.is_function_call': ('ast.html#is_function_call', 'testcell/core.py'),
                               'testcell.core.is_import_statement': ('ast.html#is_import_statement', 'testcell/core.py'),
                               'testcell.core.last_node': ('ast.html#last_node', 'testcell/core.py'),
                               'testcell.core.last_statement_has_semicolon': ('ast.html#last_statement_has_semicolon', 'testcell/core.py'),
                               'testcell.core.need_display': ('ast.html#need_display', 'testcell/core.py'),
                               'testcell.core.node_source': ('ast.html#node_source', 'testcell/core.py'),
                               'testcell.core.wrap_node': ('ast.html#wrap_node', 'testcell/core.py')}}}
