# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testcell',
                'doc_host': 'https://artste.github.io',
                'git_url': 'https://github.com/artste/testcell',
                'lib_path': 'testcell'},
  'syms': { 'testcell.core': { 'testcell.core.auto_return': ('ast.html#auto_return', 'testcell/core.py'),
                               'testcell.core.code_till_node': ('ast.html#code_till_node', 'testcell/core.py'),
                               'testcell.core.end_of_last_line_of_code': ('ast.html#end_of_last_line_of_code', 'testcell/core.py'),
                               'testcell.core.extract_call': ('ast.html#extract_call', 'testcell/core.py'),
                               'testcell.core.is_assignment': ('ast.html#is_assignment', 'testcell/core.py'),
                               'testcell.core.is_ast_node': ('ast.html#is_ast_node', 'testcell/core.py'),
                               'testcell.core.is_import_statement': ('ast.html#is_import_statement', 'testcell/core.py'),
                               'testcell.core.last_node': ('ast.html#last_node', 'testcell/core.py'),
                               'testcell.core.last_statement_has_semicolon': ('ast.html#last_statement_has_semicolon', 'testcell/core.py'),
                               'testcell.core.need_return': ('ast.html#need_return', 'testcell/core.py'),
                               'testcell.core.node_source': ('ast.html#node_source', 'testcell/core.py')}}}
